DEFAULT_SESSION_POOL_TIMEOUT = 120
PRIMARY_CONFIGURATION_FILENAME = "primary"
SECONDARY_CONFIGURATION_FILENAME = "secondary"
TEMPORARY_CONFIGURATION_FILENAME = "temporary_configuration_file"
CONFIGURATION_FILES = {"primary.cfg", "secondary.cfg"}
